- ali_alavi/week_01/calculator/main.js
- ali_alavi/week_01/strings/main.js
- readme.md
Just fixed a typo in readme for upstream url.
> Added missing '-' from upstream url.

- zara_ispahany/week1/day2/index.html
- zara_ispahany/week1/day2/js/exercises.js
> day #2 homework

- carmina_soto/week_01/day_02/calculator/index.html
- carmina_soto/week_01/day_02/calculator/js/main.js
- carmina_soto/week_01/day_02/strings/index.html
- carmina_soto/week_01/day_02/strings/js/main.js
- How difficult did you find this (out of 10)? 0 being no problems at all, 10 being impossible 
8
Strings for function notBad and fixStart
function notBad under folder "strings/js/main.js" line 102-123
Actually not sure if there's a better way of doing the function notBad. 
3 hours
> Day 2 calculator and strings homework

- ali_alavi/week_01/calculator/main.js
- ali_alavi/week_01/strings/main.js
- readme.md
- warmups/week1/day1_raindrops/main.js
> Ali Alavi - Submit

- azadeh_hakkak/week1/day1/calculator/index.html
- azadeh_hakkak/week1/day1/calculator/main.js
- How difficult did you find this (out of 10)? 
8- didnt have time to do strings.
understanding the question and analysing the last part in calculator.
i think i have to practice to redo the homework .
2 hrs
> day1 calculator homework

- frank_da/week1/day1/homework1-caculator/index.html
- frank_da/week1/day1/homework1-caculator/js/main.js
- frank_da/week1/day1/homework2/index.html
- frank_da/week1/day1/homework2/js/main.js
- frank_da/week1/day2/warmup/week1day3/index.html
- frank_da/week1/day2/warmup/week1day3/main.js
6
Replace strings
Not this time
Regular expression
2.5 hours
> day 1 homework 1 and homework 2

- mitchell_browne/week01/strings/README.md
- mitchell_browne/week01/strings/index.html
- mitchell_browne/week01/strings/js/main.js
- mitchell_browne/week01/the_calculator/README.md
- mitchell_browne/week01/the_calculator/index.html
- mitchell_browne/week01/the_calculator/js/main.js
**0**
**No, just had to look up on MDN new string methods to call**
**No**
**How to make code more succinct and know most efficient code for particular problems.**
**1 hour**
> Week01 Day 1 Calculator & Day 2 Strings

- joshua_panebianco/josh_panebianco_homework_01/index.html
- joshua_panebianco/josh_panebianco_homework_01/js/main.js
- joshua_panebianco/josh_panebianco_homework_01/strings/index.html
- joshua_panebianco/josh_panebianco_homework_01/strings/js/main.js
7
The strings sections were not easy, I need help
The strings section
The math functions in JS
around 2 hours
> day two string homework

- harish_ramesh/week1/feb11/Strings/index.html
- harish_ramesh/week1/feb11/Strings/main.js
- harish_ramesh/week1/feb11/theCalculator/index.html
- harish_ramesh/week1/feb11/theCalculator/main.js
5
where to use 'return' 
4 hrs
> the calculator & strings homework of feb11

- napoleon_manaog/week_01/hw/d2/hw-d2.js
- napoleon_manaog/week_01/hw/d2/index.html
> w1-d2 homework

- vivian_wan/week1/day2/index.html
- vivian_wan/week1/day2/js/homework.js
The first part ( Calculator incl bonus) was 4/10 ( not too much trouble)
The second part (Strings) was 9/10 (attempted the first exercise, and read through the rest of the activities.  Solving the rest of the activities didn't come naturally for me. I aim to re-visit those activities over the weekend.
- Was there anything that you struggled with? Yes rounding to 2 d.p.  which I searched and realised that i can use Tofixed.
Additionally, please refer to the above.
- Is there any particular code you want me to look into? No thank you
- Is there anything that you'd like some further information on? No thank you
- Roughly how long did it take? may be 2 hours.
@
> Viv Wan - Day 2

- kuljit_kaur/week1/day1/calculator/index.html
- kuljit_kaur/week1/day1/calculator/main.js
- kuljit_kaur/week1/day1/string/index.html
- kuljit_kaur/week1/day1/string/main.js
3 -  Bit challenging when working on Strings.
Not yet
No
No
1 hr for Calculator and nearly took 3 hrs for String
> Calculator and String

- harish_ramesh/week1/feb12/homework/index.html
- harish_ramesh/week1/feb12/homework/main.js
7
was really confused while passing an array as an argument into a function and not pretty sure with syntax thumb rules with "For" loops 
all my for loops please
string manipulation
4 hrs 30 mins
> arrays homework

- joshua_panebianco/josh_homework_02/index.html
- joshua_panebianco/josh_homework_02/js/main.js
I needed some help from Joel on this one
the logic in the if statements
around 1 hour
> Homework 02 about functions and arrays

- karthikeyan_sekar/week1/day2/Functions_part2/index.html
- karthikeyan_sekar/week1/day2/Functions_part2/js/exercises.js
> Part 2 - calculations

- napoleon_manaog/week_01/hw/d3/hw-d3.js
- napoleon_manaog/week_01/hw/d3/index.html
8
yes. But figured it out.
no
no
3
> w1-d3 homework

- mitchell_browne/week01/the_word_guesser/js/main.js
1
Bug fixing
No thanks
No thanks
1 hour
> Made hangman BETTER

- zara_ispahany/week1/day3/index.html
- zara_ispahany/week1/day3/js/exercises.js
> day 3 homework

- kuljit_kaur/week1/day3/array/index.html
- kuljit_kaur/week1/day3/array/main.js
3 
Not really.
No
No
I took little more time to do "The Word Guesser". In all took 3 hours.
> Array Exercise

- carmina_soto/week_01/day_03/bonus_material/index.html
- carmina_soto/week_01/day_03/bonus_material/js/main.js
- carmina_soto/week_01/day_03/exercise/index.html
- carmina_soto/week_01/day_03/exercise/js/main.js
- carmina_soto/week_01/day_03/warmup/index.html
- carmina_soto/week_01/day_03/warmup/js/main.js
- carmina_soto/week_01/day_03/word_guesser/index.html
- carmina_soto/week_01/day_03/word_guesser/js/main.js
6
All of the bonus part of word guesser.
None
None
2 hours (excluding the bonus part of the word guesser)
> Day 03 Homework

- lawrence_carreon/week1/d4_hw/bank/index.html
- lawrence_carreon/week1/d4_hw/bank/js/main.js
- lawrence_carreon/week1/d4_hw/credit_card/index.html
- lawrence_carreon/week1/d4_hw/credit_card/js/main.js
- lawrence_carreon/week1/d4_hw/geometry/index.html
- lawrence_carreon/week1/d4_hw/geometry/js/main.js
> "THIS" (-_-)

- mitchell_browne/week01/geometry_function_lab/README.md
- mitchell_browne/week01/geometry_function_lab/index.html
- mitchell_browne/week01/geometry_function_lab/js/main.js
- mitchell_browne/week01/the_bank/README.md
- mitchell_browne/week01/the_bank/index.html
- mitchell_browne/week01/the_bank/js/main.js
0
Researching the formulas for obtuse and area with 3 sides. Getting better (i think) at succinct-ion.
Nope
Nope
4 hours
> Week01 Day 3 Geometry and Bank

- joshua_panebianco/josh_homework_day4/index.html
- joshua_panebianco/josh_homework_day4/js/main.js
8
The credit card exercise was the one I could not get working with all the conditions 
The credit card section
Built  in JS functions 
over 2 hours
> homework for day 4

- lawrence_carreon/week1/d4_hw/bank/js/main.js
- lawrence_carreon/week1/d4_hw/credit_card/js/main.js
- lawrence_carreon/week1/day2_homework/js/main.js
> updated bank and creditcard

- frank_da/week1/day3/Javascript Bank/index.html
- frank_da/week1/day3/Javascript Bank/main.js
- frank_da/week1/day3/homework4-Geometry Function Lab/index.html
- frank_da/week1/day3/homework4-Geometry Function Lab/main.js
- frank_da/week1/day3/homework4-Geometry Function Lab/readme.md
- frank_da/week1/day3/homework5-The Cash Register/index.html
- frank_da/week1/day3/homework5-The Cash Register/main.js
- frank_da/week1/day3/homework6-Credit Card Validation/index.html
- frank_da/week1/day3/homework6-Credit Card Validation/main.js
- frank_da/week1/day3/warmup/main.js
8
change an object's value when object is in an array
In Javascript bank/main.js, line 22 to line 24. I was using a loop to change object's value. Is there a better way to change the object value directly.
```javascript
transfer: function (name1, name2, money) {
// change account1 balance first
for (let i = 0; i < this.accounts.length; i ++){
if (this.accounts[i].name === name1) {
this.accounts[i].balance -= money;
if (this.accounts[i].balance < 0) {
return '(${ this.accounts[i].name }) doesn\'t have enough balance';
} else {
console.log(`(${ this.accounts[i].name })'s balance changed to ${ …
```
> Homework 4

- lawrence_carreon/week1/mta/index.html
- lawrence_carreon/week1/mta/js/main.js
> mta homework completed

- lawrence_carreon/week1/mta/index.html
- lawrence_carreon/week1/mta/js/main.js
> Made another commit for validation I missed in my previous pull request

- napoleon_manaog/week_01/hw/d5/index.html
- napoleon_manaog/week_01/hw/d5/mta-w1d5.js
> MTA w1d5 sol1

- carmina_soto/week_01/day_05/exercise/index.html
- carmina_soto/week_01/day_05/exercise/js/main.js
- carmina_soto/week_01/day_05/homework/index.html
- carmina_soto/week_01/day_05/homework/js/main.js
- carmina_soto/week_01/day_05/warmup/index.html
- carmina_soto/week_01/day_05/warmup/js/main.js
7
logic part of the code
none at the moment
none at the moment
3 hours
> Week 01 Day 05 MTA Homework

- frank_da/week1/day4/mta-1/index.html
- frank_da/week1/day4/mta-1/main.js
- frank_da/week1/day4/mta-1/readme.md
7
Struggled at beginning when designning how to make programs working.
Any tips for designing pattern for a program? I would definitely get lost in this homework without hints. 
2 hours
> MTA homework

- zara_ispahany/02week/02day/homework/css/style.css
- zara_ispahany/02week/03day/02exercises/index.html
- zara_ispahany/02week/03day/02exercises/main.js
- zara_ispahany/02week/03day/02exercises/style.css
- zara_ispahany/02week/03day/03exercises/index.html
- zara_ispahany/02week/03day/03exercises/main.js
- zara_ispahany/02week/03day/exercises/aboutme.html
- zara_ispahany/02week/03day/exercises/main.js
- zara_ispahany/02week/03day/exercises/style.css
- zara_ispahany/02week/03day/homework/index.html
- zara_ispahany/02week/03day/homework/jquery.js
- zara_ispahany/02week/03day/homework/main.js
- zara_ispahany/02week/04day/exercises/index.html
- zara_ispahany/02week/04day/exercises/main.js
- zara_ispahany/02week/04day/jqueryex/index.html
- zara_ispahany/02week/04day/jqueryex/js/jquery.js
- zara_ispahany/02week/04day/jqueryex/js/main.js
- zara_ispahany/02week/04day/warmup/index.html
- zara_ispahany/02week/04day/warmup/main.js
- zara_ispahany/02week/04day/youtubeex/index.html
- zara_ispahany/02week/04day/youtubeex/js/jquery.js
- zara_ispahany/02week/04day/youtubeex/js/main.js
- zara_ispahany/02week/05day/exercises/index.html
- zara_ispahany/02week/05day/exercises/jquery.js
- zara_ispahany/02week/05day/warmup/index.html
- zara_ispahany/02week/05day/warmup/jquery.js
- zara_ispahany/02week/05day/warmup/main.js
> day 2,3,4 homework

- lawrence_carreon/w6/googlebooks_ajax_nojquery/css/style.css
- lawrence_carreon/w6/googlebooks_ajax_nojquery/index.html
- lawrence_carreon/w6/googlebooks_ajax_nojquery/js/main.js
> ajax google books (no pagination)

- karthikeyan_sekar/HW_Ajax_books/js/books.js
- karthikeyan_sekar/week7/HW_Ajax_covid19/index.html
- karthikeyan_sekar/week7/HW_Ajax_covid19/js/exercise.js
- karthikeyan_sekar/week7/HW_Ajax_covid19/js/jquery.js
5
finding the correct object
1hr
> covid 19 - Ajax app

- joshua_panebianco/week10/node-intro/00-hello.js
- joshua_panebianco/week10/node-intro/01-file-io.js
- joshua_panebianco/week10/node-intro/flintstones.txt
- joshua_panebianco/week10/node-intro/package-lock.json
- joshua_panebianco/week10/node-intro/package.json
I don't really understand this, I found the git pages notes difficult to understand. I felt like I was just coping the code but not understanding what is going on. This reminds me that I only work on the front end after this course.
> node homework
